/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DeployChallenge,
  DeployChallengeInterface,
} from "../DeployChallenge";

const _abi = [
  {
    inputs: [],
    name: "isComplete",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b88061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b2fa1c9e14602d575b600080fd5b60336047565b604051603e9190605d565b60405180910390f35b60006001905090565b6057816076565b82525050565b6000602082019050607060008301846050565b92915050565b6000811515905091905056fea2646970667358221220f2cd7339cd2552ca580f6c5ad24e103055c211aa47a2e1c36ceda19f5d32352964736f6c63430008040033";

type DeployChallengeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DeployChallengeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DeployChallenge__factory extends ContractFactory {
  constructor(...args: DeployChallengeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DeployChallenge> {
    return super.deploy(overrides || {}) as Promise<DeployChallenge>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DeployChallenge {
    return super.attach(address) as DeployChallenge;
  }
  override connect(signer: Signer): DeployChallenge__factory {
    return super.connect(signer) as DeployChallenge__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DeployChallengeInterface {
    return new utils.Interface(_abi) as DeployChallengeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DeployChallenge {
    return new Contract(address, _abi, signerOrProvider) as DeployChallenge;
  }
}
